name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'coverage/**'
      - '**.md'
    tags:
      - 'v*.*.*'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'coverage/**'
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate (runs everything)
        run: npm run validate

  changeset:
    name: Changeset
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Changeset
        uses: changesets/action@v1
        with:
          publish: false
