name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'coverage/**'
      - '**.md'
    tags:
      - 'v*.*.*'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'coverage/**'
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate (runs everything)
        run: npm run validate

  changeset:
    name: Changeset
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check changesets
        id: check_changesets
        shell: bash
        run: |
          echo "Checking for changesets..."
          if [ -n "$(find .changeset -name '*.md' ! -name 'README.md')" ]; then
            echo "has_changesets=true" >> $GITHUB_OUTPUT
          else
            echo "No changeset files found."
            echo "has_changesets=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup NodeJs
        if: steps.check_changesets.outputs.has_changesets == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        if: steps.check_changesets.outputs.has_changesets == 'true'
        run: npm ci

      - name: Run Changeset
        if: steps.check_changesets.outputs.has_changesets == 'true'
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
        with:
          publish: false
